### PR TITLE
Responsive issues & How to donate page

### PR DESCRIPTION
**Pull request by shaminmeerankutty**

### CODE REVIEW

**Comment by shaminmeerankutty** [comment]
@nakule React Router is not routing as the home link is having `index.html`. So I haven't added the routing. How can I fix that?

**Comment by shaminmeerankutty** [comment]
fixed #36 #11

**Comment by nakule** [comment]
@shaminmeerankutty 
That is only going to be a minor developmental issue, 
1. You can simply static serve the dist folder, instead of using django's static server
2. Inside `urls.py` you can specify path as `index.html` for static files so that `/` will serve `/index.html`

**Comment by shaminmeerankutty** [comment]
@nakule Added `/how-to-donate` route for How to donate page

**Comment by nakule** [comment]
@shaminmeerankutty Let me know when this is ready to be merged.

**Comment by shaminmeerankutty** [comment]
@nakule It is ready to be merged.

**Comment by nakule** [comment]
@shaminmeerankutty can you please resolve the conflict above?

**Pull request merged**
